# Generated by Django 5.0 on 2023-12-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Site name')),
                ('text', models.TextField(verbose_name='Enter your text')),
                ('button1', models.CharField(max_length=30, verbose_name='main button name')),
                ('button2', models.CharField(max_length=30, verbose_name='Home button name')),
                ('button3', models.CharField(max_length=30, verbose_name='what we do button name')),
                ('button4', models.CharField(max_length=30, verbose_name='testimionals button name')),
                ('button5', models.CharField(max_length=30, verbose_name='Gallery  button name')),
                ('button6', models.CharField(max_length=30, verbose_name='Contact button name')),
            ],
        ),
    ]
