# Generated by Django 5.0 on 2023-12-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Testimonial name')),
                ('text', models.TextField(verbose_name='Enter your text')),
                ('image', models.ImageField(upload_to='image', verbose_name='Worker image')),
                ('about', models.TextField(verbose_name='CV Worker')),
                ('names', models.TextField(verbose_name='worker name')),
            ],
        ),
    ]
