# Generated by Django 5.0 on 2023-12-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_testimonials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='name',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='text',
        ),
    ]
