# Generated by Django 5.0 on 2023-12-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_testimonials_name_remove_testimonials_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Gallery name')),
                ('text', models.TextField(verbose_name='Enter your text')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image', verbose_name=' image')),
                ('button', models.CharField(max_length=50, verbose_name='button name')),
                ('button1', models.CharField(max_length=50, verbose_name='button name')),
            ],
        ),
    ]
