# Generated by Django 5.0 on 2023-12-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_gallery_button1_alter_gallery_button'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50, verbose_name='Contact name')),
                ('text', models.TextField(verbose_name='Enter your text')),
                ('name', models.CharField(max_length=50, verbose_name='Contact name')),
                ('email', models.CharField(max_length=50, verbose_name='Contact email')),
                ('message', models.TextField(verbose_name='Contact message')),
            ],
        ),
    ]
