# Generated by Django 5.0 on 2023-12-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_contact_pname_remove_contact_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='last',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50, verbose_name='page name')),
                ('text', models.TextField(verbose_name='Enter your text')),
                ('button', models.CharField(max_length=20, verbose_name='chat name')),
                ('button1', models.CharField(max_length=20, verbose_name='location name')),
                ('button2', models.CharField(max_length=20, verbose_name='mail name')),
                ('button3', models.CharField(max_length=20, verbose_name='number ')),
            ],
        ),
    ]
