# Generated by Django 5.0 on 2023-12-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_last'),
    ]

    operations = [
        migrations.AlterField(
            model_name='last',
            name='button',
            field=models.CharField(max_length=30, verbose_name='chat name'),
        ),
        migrations.AlterField(
            model_name='last',
            name='button1',
            field=models.CharField(max_length=30, verbose_name='mail name'),
        ),
        migrations.AlterField(
            model_name='last',
            name='button2',
            field=models.CharField(max_length=30, verbose_name='location name'),
        ),
        migrations.AlterField(
            model_name='last',
            name='button3',
            field=models.CharField(max_length=30, verbose_name='number '),
        ),
    ]
